Improve test
rgarcia11/protractor-workshop-2017 pull request #2
Opened 2018-07-16 20:02 UTC by rgarcia11

2018-07-16 22:16 UTC, aperdomob requested changes

2018-07-16 22:16 UTC, aperdomob commented on protractor.config.js
> +<<<<<<< HEAD
corregir estos conflictos de código

2018-07-17 14:00 UTC, rgarcia11 commented on protractor.config.js
> +<<<<<<< HEAD
ya hice otro commit

2018-07-17 14:04 UTC, aperdomob approved these changes

2018-07-17 14:05 UTC, merged